- README.md
This pr fixes the broken pr link in **Our Contribution Process** section
Closes #14
-   Fixed link issues
-   [x] Follows contribution guidelines
-   [x] Uses correct Markdown format
-   [x] Tested rendering in preview
> [fix] Correct broken pr template link in contribution process

- interview-qna/topic-wise/go-routine.md
Top 15 interview questions with answers on go-routines has been listed.
None
- Added go-routine.md file under topic-wise interview question section
> Add sample interview qna for go-routines

- docs/interview-qna/class-wise/golang016-package-scope/README.md
- docs/interview-qna/class-wise/golang017-scope-example/README.md
- docs/interview-qna/class-wise/golang018-variable-shadowing/README.md
- docs/interview-qna/class-wise/golang019-function-types/README.md
- docs/interview-qna/class-wise/golang020-init-function/README.md
- docs/interview-qna/class-wise/golang021-anonymous-func-and-iife/README.md
- docs/interview-qna/class-wise/golang022-function-expression-example/README.md
- docs/interview-qna/class-wise/golang023-fof-vs-hof/README.md
- docs/interview-qna/class-wise/golang024-internal-memory/README.md
- docs/interview-qna/class-wise/golang025-end_of_internal-memory/README.md
- docs/interview-qna/class-wise/golang026-closure/README.md
- docs/interview-qna/class-wise/golang027-struct/README.md
- docs/interview-qna/class-wise/golang028-receiver-function/README.md
- docs/interview-qna/class-wise/golang029-array/README.md
- docs/interview-qna/class-wise/golang030-pointers/README.md
- docs/interview-qna/class-wise/golang030-pointers/main.go
- docs/interview-qna/class-wise/golang031-slice/README.md
- docs/interview-qna/class-wise/golang031-slice/main.go
- interview-qna/class-wise/golang031-slice/README.md
- interview-qna/class-wise/golang031-slice/main.go
What this PR adds and improves.
- Added class-notes-30-pointer.md
- Added class-notes-31-slice.md
- Modified other class-wise notes for updates and improvements
> feat: Add and update class-wise notes

- docs/warp/cp-guide.md
What this PR adds/fixes/improves:
1. Add more resources on the CP-guide
2. Add recent daily contest problems
None
- Updated [docs/warp/cp-guide.md]
> Add resources and more cp problems to the cp-guide

- docs/warp/cp-guide.md
What this PR adds/fixes/improves:
1. Update the cp guide
2. Fix the problem numbers in the cp-guide
3. Add a session description to the cp guide
None
- Added/Updated [docs/warp/cp-guide.md]
> feat: Add session and update the cp-guide

- docs/warp/cp-guide.md
fixes the Problem number order on cp guide
None
- Updated [docs/warp/cp-guide.md]
> fix: Just a little fix to Problem number orders

- docs/warp/cp-guide.md
What this PR adds/improves:
1. Add recent CP sessions summery 
2. Add another CP resources
3. Add recent contest links
4. Add more CP problems 
None
- Updated [docs/warp/cp-guide.md]
- Add more contents
> feat: Add recent cp session summery and some other resources

- docs/interview-qna/class-wise/golang035-BP-SP/README.md
This PR adds Bengali translation for class note 35 on SP BP
Closes #
- Added README file for Bengali translation of class note 35 on SP BP
> Add Bengali translation for class note 35 on SP BP

- docs/low-level/global-vars-memory.md
Documentation of memory layout
> feat: add memory layout explanation for global variables

- category/go.mod
- server/README.md
- server/go.mod
- server/main/categories.go
- server/main/main.go
- server/rbac/README.md
- server/rbac/superadmin.go
What this PR adds/fixes/improves.
Closes #
- Removed the /category folder
- Re-structured the backend root to /server
- Added rbac for superadmin(for now all of us are superadmin)
- Added a README.md file explaining what every files does and how this structure make sense
> feat: Updated the backend structure inside /server

- server/README.md
- server/categories/categories.go
- server/main.go
No one fixed the structure and gave a PR! so here I go!
Closes #
- Fixed Structure of /server
> fix: Fixed the structure of the server slightly

- server/README.md
- server/categories/classnotes/classnotes.go
- server/main.go
Added classnotes subcategory
Closes #[]
- Added/Updated [server/category/classnotes/classnotes.go]
- Updated [server/main.go, server/README.md]
> feat: Added class-notes subcategory

- docs/warp/cp-session-log.md
Added CP Session task log and updated cp session main log
Closes #
- Added/Updated [warp/cp-session-log]
> feat: Updated cp session log and Add cp session task log

- docs/mini-projects/ecommerce/README.md
- docs/mini-projects/ecommerce/go.mod
- docs/mini-projects/ecommerce/main.go
What this PR adds/fixes/improves.
Closes #[issue-number]
- Added/ecommerce project [category/mini-projects/ecommerce]
- Fixed formatting/link issues
> feat:  Add ecommerce project folder

- ecommerce/main.go
Adds createProduct endpoint to handle product creation via POST request.
Closes #
- Added/Updated [ecommerce/main.go]
> [product] (feat/create-product): Add createProduct endpoint for adding new products

- docs/contribution-guide/TRANSLATION-GUIDE.md
Adds a Bangla translation style guide to ensure clarity, consistency, and natural tone in all localized documentation.
Closes #
- Added `docs/contribution-guides/bn-translation.md`
- Provided clear rules for writing natural Bangla
- Included do's and don'ts with examples
- Ensured consistency with archive content tone
> [docs] (docs/translation-guide): Add BGCE bangla translation guide

- docs/interview-qna/class-wise/golang046-go-runtime/README.md
- docs/interview-qna/class-wise/golang046-go-runtime/go.mod
- docs/interview-qna/class-wise/golang046-go-runtime/main.go
This PR adds Bengali Notes on **Class 46: Go Runtime**
- Added `docs/interview-qna/class-wise/golang046-go-runtime/README.md`
-  Added codes used in the class
> [docs] (docs/archive-book): Add Bengali Notes on Class 46: Go Runtime

- cortex/category/delete_category.go
- cortex/category/delete_category_test.go
- cortex/category/mock/category_repo.go
- cortex/category/mock/delete_category_test_data.go
- cortex/category/port.go
- cortex/pkg/custom_errors/errors.go
- cortex/repo/category.go
- cortex/repo/delete_category_test.go
- cortex/repo/mock/delete_category_test_data.go
- cortex/rest/handlers/delete_category.go
- cortex/rest/handlers/delete_category_test.go
- cortex/rest/handlers/handler.go
- cortex/rest/handlers/mock/category_service.go
- cortex/rest/handlers/mock/delete_category_test_data.go
- cortex/rest/swagger/swagger.json
Implements Delete Category
Closes #[195]
- cortex/handlers, cortex/category, cortex/repo
> [category] (feat/delete_category): Delete category with id

- cortex/docs/api-docs/README.md
Updates api docs - create category
- cortex/docs/api-docs
> [cortex] (patch/api-docs): Update api docs - Create Category

- cortex/Dockerfile
- cortex/docker-compose.yml
due to update of our database builder in the previous configuration , our docker compose file   
BGCE_DB_DSN: "postgres://postgres:postgres@postgres:5432/bgce?sslmode=disable
BGCE_DB_DRIVER: "postgres" 
need to updated
> [cortex](fix/docker-configuration):update the db bulider migration path
